---
# Logstash Setup
    - name: Creates /data directory
      file:
        path: /data
        state: directory
        mode: "u=rwx,g=rwx,o=rwx"
    - name: Download logstash tar ball
      get_url:
        url: https://artifacts.elastic.co/downloads/logstash/logstash-6.4.0.tar.gz
        dest: /data/logstash-6.4.0.tar.gz
        mode: 0755
    - name: unzip logstash
      unarchive:
        src: /data/logstash-6.4.0.tar.gz
        dest: /data/
        remote_src: yes
        creates: /data/logstash-6.4.0/conf.d/inputs.conf
    - name: logstash systemd copy
      template:
        src: elk_config/templates/logstash.service.j2
        dest: /etc/systemd/system/logstash.service
        mode: 0644
    - name: logstash - add start/stop script
      template:
        src: elk_config/templates/start.sh.j2
        dest: /data/logstash-6.4.0/start.sh
        mode: 0754
    - name: Creates /data/logstash-6.4.0/conf.d directory
      file:
        path: /data/logstash-6.4.0/conf.d
        state: directory
        mode: "u=rwx,g=rwx,o=rwx"
    - name: Update default logstash config
      template:
        src: elk_config/templates/inputs.conf.j2
        dest: /data/logstash-6.4.0/conf.d/inputs.conf
        mode: 0660
    - name: force systemd reload
      systemd:
        daemon_reload: yes
    - name: Start the logstash service
      service:
        name: logstash
        state: started
        enabled: yes

